name: fixonnextupdate
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'allowlist'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Thank you for your support. The domain(s) has/have been added to the allowlist and will be removed with the next full release at the latest. A full release is usually performed every 24 hours.
