name: scam
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'scam/phishing'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Thank you, ping @durablenapkin @jarelllama @iam-py-test for checking and possibly including the domain(s).
